//
// Generated file, do not edit! Created by opp_msgtool 6.0 from gradys_simulations/protocols/messages/internal/MobilityCommand.msg.
//

#ifndef __GRADYS_SIMULATIONS_MOBILITYCOMMAND_M_H
#define __GRADYS_SIMULATIONS_MOBILITYCOMMAND_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace gradys_simulations {

class MobilityCommand;

}  // namespace gradys_simulations


namespace gradys_simulations {

/**
 * Enum generated from <tt>gradys_simulations/protocols/messages/internal/MobilityCommand.msg:19</tt> by opp_msgtool.
 * <pre>
 * // Commands that the mobility module should be capable of carrying out
 * enum MobilityCommandType
 * {
 *     // Makes the drone reverse on its course
 *     // No params
 *     REVERSE = 0;
 * 
 *     // Makes the drone travel to a specific waypoint, following the tour pack
 *     // Param 1: Waypoint index
 *     GOTO_WAYPOINT = 1;
 * 
 *     // Makes the drone go to a specific coordinate and orient itself so it can continue the tour afterwards
 *     // Param 1: x component of the coord
 *     // Param 2: y component of the coord
 *     // Param 3: z component of the coord
 *     // Param 4: Next waypoint (Waypoint the drone should go to after reaching the target)
 *     // Param 5: Last waypoint (Waypoint the drone used to reach the coords)
 *     GOTO_COORDS = 2;
 * 
 *     // Orders the drone to return to the home coordinates
 *     // No params
 *     RETURN_TO_HOME = 3;
 * 
 *     // Idles the drone for a specified time
 *     // Param 1: idle time in seconds
 *     IDLE_TIME = 4;
 * 
 *     // Simulates vehicle recharging. Basically a combination of the RETURN_TO_HOME and IDLE_TIME commands
 *     // Param 1: Time to recharge
 *     RECHARGE = 5;
 * 
 *     // Shuts down the drone, making it land and permanently stay idle
 *     // This command is special as it takes priority over other commands
 *     // No params
 *     FORCE_SHUTDOWN = 6;
 * 
 *     // Cancels an active FORCE_SHUTDOWN command
 *     // No params
 *     WAKE_UP = 7;
 * }
 * </pre>
 */
enum MobilityCommandType {
    REVERSE = 0,
    GOTO_WAYPOINT = 1,
    GOTO_COORDS = 2,
    RETURN_TO_HOME = 3,
    IDLE_TIME = 4,
    RECHARGE = 5,
    FORCE_SHUTDOWN = 6,
    WAKE_UP = 7
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MobilityCommandType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MobilityCommandType& e) { int n; b->unpack(n); e = static_cast<MobilityCommandType>(n); }

/**
 * Class generated from <tt>gradys_simulations/protocols/messages/internal/MobilityCommand.msg:59</tt> by opp_msgtool.
 * <pre>
 * // Message declaration containing the command Id and its parameters 
 * message MobilityCommand
 * {
 *     MobilityCommandType commandType;
 *     double param1 = -1;
 *     double param2 = -1;
 *     double param3 = -1;
 *     double param4 = -1;
 *     double param5 = -1;
 * }
 * </pre>
 */
class MobilityCommand : public ::omnetpp::cMessage
{
  protected:
    MobilityCommandType commandType = static_cast<gradys_simulations::MobilityCommandType>(-1);
    double param1 = -1;
    double param2 = -1;
    double param3 = -1;
    double param4 = -1;
    double param5 = -1;

  private:
    void copy(const MobilityCommand& other);

  protected:
    bool operator==(const MobilityCommand&) = delete;

  public:
    MobilityCommand(const char *name=nullptr, short kind=0);
    MobilityCommand(const MobilityCommand& other);
    virtual ~MobilityCommand();
    MobilityCommand& operator=(const MobilityCommand& other);
    virtual MobilityCommand *dup() const override {return new MobilityCommand(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual MobilityCommandType getCommandType() const;
    virtual void setCommandType(MobilityCommandType commandType);

    virtual double getParam1() const;
    virtual void setParam1(double param1);

    virtual double getParam2() const;
    virtual void setParam2(double param2);

    virtual double getParam3() const;
    virtual void setParam3(double param3);

    virtual double getParam4() const;
    virtual void setParam4(double param4);

    virtual double getParam5() const;
    virtual void setParam5(double param5);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MobilityCommand& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MobilityCommand& obj) {obj.parsimUnpack(b);}


}  // namespace gradys_simulations


namespace omnetpp {

template<> inline gradys_simulations::MobilityCommand *fromAnyPtr(any_ptr ptr) { return check_and_cast<gradys_simulations::MobilityCommand*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __GRADYS_SIMULATIONS_MOBILITYCOMMAND_M_H

