//
// Generated file, do not edit! Created by opp_msgtool 6.0 from gradys_simulations/protocols/messages/network/DadcaMessage.msg.
//

#ifndef __INET_DADCAMESSAGE_M_H
#define __INET_DADCAMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class DadcaMessage;

}  // namespace inet

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Enum generated from <tt>gradys_simulations/protocols/messages/network/DadcaMessage.msg:22</tt> by opp_msgtool.
 * <pre>
 * enum DadcaMessageType
 * {
 *     HEARTBEAT = 0;
 *     PAIR_REQUEST = 1;
 *     PAIR_CONFIRM = 2;
 *     BEARER = 3;
 * }
 * </pre>
 */
enum DadcaMessageType {
    HEARTBEAT = 0,
    PAIR_REQUEST = 1,
    PAIR_CONFIRM = 2,
    BEARER = 3
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DadcaMessageType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DadcaMessageType& e) { int n; b->unpack(n); e = static_cast<DadcaMessageType>(n); }

/**
 * Class generated from <tt>gradys_simulations/protocols/messages/network/DadcaMessage.msg:30</tt> by opp_msgtool.
 * <pre>
 * class DadcaMessage extends FieldsChunk
 * {
 *     chunkLength = B(34); // Fixed chunk length
 *     int sourceID = -1;  // ID of the message's source
 *     int destinationID = -1; // ID of the message's destination
 *     int nextWaypointID = -1; // ID of the next waypoint
 *     int lastWaypointID = -1; // ID of the last waypoint
 *     int dataLength = 5; // Length of the imaginary data being carried in the message
 *     int leftNeighbours = 0; // Neighbours to the left of the drone
 *     int rightNeighbours = 0; // Neighbours to the right of the drone
 *     bool reversed = false; // Reverse flag which indicates the current direction the drone is travelling in
 *     DadcaMessageType messageType = HEARTBEAT; // Type of message
 * }
 * </pre>
 */
class DadcaMessage : public ::inet::FieldsChunk
{
  protected:
    int sourceID = -1;
    int destinationID = -1;
    int nextWaypointID = -1;
    int lastWaypointID = -1;
    int dataLength = 5;
    int leftNeighbours = 0;
    int rightNeighbours = 0;
    bool reversed = false;
    DadcaMessageType messageType = HEARTBEAT;

  private:
    void copy(const DadcaMessage& other);

  protected:
    bool operator==(const DadcaMessage&) = delete;

  public:
    DadcaMessage();
    DadcaMessage(const DadcaMessage& other);
    virtual ~DadcaMessage();
    DadcaMessage& operator=(const DadcaMessage& other);
    virtual DadcaMessage *dup() const override {return new DadcaMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSourceID() const;
    virtual void setSourceID(int sourceID);

    virtual int getDestinationID() const;
    virtual void setDestinationID(int destinationID);

    virtual int getNextWaypointID() const;
    virtual void setNextWaypointID(int nextWaypointID);

    virtual int getLastWaypointID() const;
    virtual void setLastWaypointID(int lastWaypointID);

    virtual int getDataLength() const;
    virtual void setDataLength(int dataLength);

    virtual int getLeftNeighbours() const;
    virtual void setLeftNeighbours(int leftNeighbours);

    virtual int getRightNeighbours() const;
    virtual void setRightNeighbours(int rightNeighbours);

    virtual bool getReversed() const;
    virtual void setReversed(bool reversed);

    virtual DadcaMessageType getMessageType() const;
    virtual void setMessageType(DadcaMessageType messageType);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DadcaMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DadcaMessage& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::DadcaMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::DadcaMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_DADCAMESSAGE_M_H

